Repository gnosis/gp-ui, pull requests merged in 2021-09, with the labels that each got.

#581 1042 create card child component
  src/assets/img/question1.svg
  src/components/common/Card/CardContent.tsx
  src/components/common/CardRow/CardRow.stories.tsx
Labels: Auto-merge

#569 Add TradesTable component
  src/api/operator/types.ts
  src/components/common/CopyButton/index.tsx
  src/components/common/DateDisplay/index.tsx
  src/components/common/RowWithCopyButton/index.tsx
  src/components/common/SimpleTable/index.stories.tsx
  src/components/common/SimpleTable/index.tsx
  src/components/common/StyledUserDetailsTable.tsx
  src/components/orders/DetailsTable/index.tsx
  src/components/orders/OrderDetails/index.tsx
  src/components/orders/OrdersUserDetailsTable/index.tsx
  src/components/trade/TradesTable/Surplus.tsx
  src/components/trade/TradesTable/index.stories.tsx
  src/components/trade/TradesTable/index.tsx
  src/utils/format.ts
  src/utils/operator.ts
  test/data/operator.ts
Labels: Protofire

#611 1046 load from api orderstable
  src/api/operator/operatorApi.ts
  src/api/operator/types.ts
  src/apps/explorer/ExplorerApp.tsx
  src/apps/explorer/components/OrdersTableWidget/OrdersTableWithData.tsx
  src/apps/explorer/components/OrdersTableWidget/context/OrdersTableContext.tsx
  src/apps/explorer/components/OrdersTableWidget/index.tsx
  src/apps/explorer/components/OrdersTableWidget/useGetOrders.tsx
  src/apps/explorer/components/common/ExplorerTabs/ExplorerTab.tsx
  src/apps/explorer/const.ts
  src/apps/explorer/pages/UserDetails.tsx
  src/components/common/StyledUserDetailsTable.tsx
  src/components/orders/OrdersUserDetailsTable/index.tsx
  src/hooks/useOperatorOrder.ts
  src/utils/operator.ts
  test/utils/operator/orderFormatAmount.test.ts
Labels: Protofire

#658 Order not found UI
  src/assets/img/support.png
  src/components/orders/OrderDetails/index.tsx
  src/components/orders/OrderNotFound/index.tsx
  src/components/orders/Search/Search.styled.ts
  src/components/orders/Search/index.tsx
  src/hooks/useSearchSubmit.ts
  src/theme/styles/fonts.ts
Labels: app:Explorer, Protofire, Auto-merge

#661 New api orderstable
  src/api/operator/index.ts
  src/api/operator/operatorApi.ts
  src/api/operator/operatorMock.ts
  src/api/operator/types.ts
  src/apps/explorer/components/OrdersTableWidget/useGetOrders.tsx
Labels: app:Explorer, Protofire, Auto-merge

#686 670 component order limiter
  src/apps/explorer/components/OrdersTableWidget/PaginationOrdersTable.tsx
  src/apps/explorer/components/OrdersTableWidget/context/OrdersTableContext.tsx
  src/apps/explorer/components/OrdersTableWidget/index.tsx
  src/apps/explorer/components/OrdersTableWidget/useGetOrders.tsx
  src/apps/explorer/components/OrdersTableWidget/useTable.tsx
  src/apps/explorer/components/common/Dropdown/Dropdown.stories.tsx
  src/apps/explorer/components/common/Dropdown/index.tsx
  src/apps/explorer/components/common/Dropdown/styled.tsx
  src/hooks/useOnClickOutside.tsx
Labels: app:Explorer, Protofire, Auto-merge

#682 [Explorer] Add local timezone on date fields
  src/components/Tooltip.tsx
  src/components/common/DateDisplay/index.tsx
Labels: Protofire, Auto-merge
