Repository gnosis/gp-ui, pull requests merged in 2021-10, with the labels that each got.

#694 Create buttons component to paginate user orders table
  package.json
  src/apps/explorer/components/OrdersTableWidget/OrdersTableWithData.tsx
  src/apps/explorer/components/OrdersTableWidget/PaginationOrdersTable.tsx
  src/apps/explorer/components/OrdersTableWidget/context/OrdersTableContext.tsx
  src/apps/explorer/components/OrdersTableWidget/index.tsx
  src/apps/explorer/components/OrdersTableWidget/useGetOrders.tsx
  src/apps/explorer/components/OrdersTableWidget/useTable.tsx
  src/hooks/useFirstRender.tsx
  test/hooks/useTable.test.tsx
  test/utils/paginationHelper.test.ts
  yarn.lock
Labels: app:Explorer, Protofire, Auto-merge

#701 404 error page
  src/apps/explorer/pages/NotFound.tsx
Labels: app:Explorer, Protofire, Auto-merge

#727 Order list style
  src/components/common/SimpleTable/index.tsx
  src/components/orders/DetailsTable/index.tsx
Labels: app:Explorer, Protofire, Auto-merge, ⬇ Low

#726 Adding LinkWithPrefixNetwork
  src/components/common/LinkWithPrefixNetwork/index.tsx
  src/components/orders/DetailsTable/index.tsx
  src/state/network/updater.tsx
  test/hooks/useDecomposedPath.test.tsx
Labels: app:Explorer, Protofire, Auto-merge

#766 Reuse LinkWithPrefixNetwork in orders/trades table
  src/components/orders/OrdersUserDetailsTable/index.tsx
  src/components/trade/TradesTable/index.tsx
Labels: app:Explorer, Protofire, Auto-merge

#721 [Explorer] Orders table responsive
  src/apps/explorer/components/OrdersTableWidget/PaginationOrdersTable.tsx
  src/apps/explorer/components/common/ExplorerTabs/ExplorerTab.tsx
  src/components/common/CopyButton/index.tsx
  src/components/common/Tabs/Tabs.tsx
  src/components/orders/OrdersUserDetailsTable/index.tsx
Labels: Protofire, Auto-merge

#782 Add a default formatting of amount
  src/apps/explorer/components/common/TextWithTooltip/index.tsx
  src/apps/explorer/const.ts
  src/components/orders/OrdersUserDetailsTable/index.tsx
  src/utils/format.ts
  src/utils/operator.ts
Labels: app:Explorer, Protofire
