Repository gnosis/gp-ui, pull requests merged in 2021-11, with the labels that each got.

#819 [Explorer] Add copy buttons for traded token addresses
  src/components/orders/AmountsDisplay/index.tsx
Labels: Protofire, Auto-merge

#815 Adding Spinner if there is not text in rows
  src/components/orders/OrdersUserDetailsTable/index.tsx
Labels: Protofire

#827 [Explorer] Properly show tokens with 0 decimals
  src/components/orders/AmountsDisplay/index.tsx
  src/services/helpers/getErc20Info.ts
Labels: 🐞 Bug, Protofire

#838 Release/2.4.0
  .github/ISSUE_TEMPLATE/epic.md
  .github/workflows/epics.yml
  src/abis/erc20_bytes32.json
  src/api/erc20/Erc20Api.ts
  src/api/erc20/Erc20ApiMock.ts
  src/api/operator/types.ts
  src/apps/explorer/components/OrdersTableWidget/OrdersTableWithData.tsx
  src/apps/explorer/components/OrdersTableWidget/PaginationOrdersTable.tsx
  src/apps/explorer/components/OrdersTableWidget/context/OrdersTableContext.tsx
  src/apps/explorer/components/OrdersTableWidget/index.tsx
  src/apps/explorer/components/OrdersTableWidget/useGetOrders.tsx
  src/apps/explorer/components/OrdersTableWidget/useSearchInAnotherNetwork.tsx
  src/apps/explorer/components/common/Search/index.tsx
  src/apps/explorer/components/common/TextWithTooltip/index.tsx
  src/apps/explorer/const.ts
  src/apps/explorer/pages/Home/index.tsx
  src/apps/explorer/pages/UserDetails.tsx
  src/components/common/DateDisplay/index.tsx
  src/components/common/TokenDisplay/index.tsx
  src/components/orders/AmountsDisplay/index.tsx
  src/components/orders/OrdersUserDetailsTable/index.tsx
  src/components/orders/StatusLabel/StatusLabel.stories.tsx
  src/components/orders/StatusLabel/index.tsx
  src/hooks/useOperatorOrder.ts
  src/hooks/useSearchSubmit.ts
  src/services/helpers/getErc20Info.ts
  src/utils/format.ts
  src/utils/miscellaneous.ts
  src/utils/operator.ts
  test/api/ExchangeApi/Erc20ApiMock.test.ts
  test/data/operator.ts
  test/data/unregisteredTokens.ts
  test/utils/format.spec.ts
  test/utils/miscellaneous.spec.ts
  test/utils/operator/orderStatus.test.ts
  yarn.lock
Labels: app:Explorer, Protofire

#858 Release v2.4.0
  package.json
Labels: app:Explorer, Protofire

#866 Signing status styles
  src/api/operator/types.ts
  src/components/orders/StatusLabel/StatusLabel.stories.tsx
  src/components/orders/StatusLabel/index.tsx
Labels: app:Explorer, Protofire, Auto-merge

#828 Add SearchNotFound page
  src/apps/explorer/ExplorerApp.tsx
  src/apps/explorer/components/common/Search/index.tsx
  src/apps/explorer/pages/Order.tsx
  src/apps/explorer/pages/SearchNotFound.tsx
  src/apps/explorer/pages/UserDetails.tsx
  src/apps/explorer/pages/styled.tsx
  src/components/RedirectToSearch.tsx
  src/components/orders/OrderDetails/index.tsx
  src/components/orders/OrderNotFound/index.tsx
  src/hooks/useSanitizeOrderIdAndUpdateUrl.ts
  src/hooks/useSearchSubmit.ts
  test/hooks/useSearchSubmit.test.tsx
  test/utils/miscellaneous.spec.ts
Labels: app:Explorer, Protofire, Auto-merge

#868 Tooltips - increase tap area
  src/components/common/DateDisplay/index.tsx
  src/components/orders/DetailsTable/index.tsx
Labels: app:Explorer, 📱Mobile, Protofire, Auto-merge
