Repository gnosis/gp-ui, pull requests merged in 2022-01, with the labels that each got.

#929 Rebranding: CoW Protocol Explorer
  config-default.yaml
  src/apps/explorer/layout/Header.tsx
  src/apps/explorer/pages/Home/index.tsx
  src/assets/img/CowProtocol-icon.svg
  src/assets/img/CowProtocol-logo-white.svg
  src/components/layout/GenericLayout/Header/index.tsx
  test/config.spec.ts
  webpack.config.js
Labels: app:Explorer, Protofire, Auto-merge, 🔥 Critical

#899 Validate if query isATxHash
  src/apps/explorer/components/TransactionsTableWidget/index.tsx
  src/apps/explorer/components/common/Search/index.tsx
  src/apps/explorer/pages/TransactionDetails.tsx
  src/components/orders/OrderNotFound/index.tsx
  src/hooks/useSearchSubmit.ts
  src/utils/miscellaneous.ts
  test/utils/miscellaneous.spec.ts
Labels: app:Explorer, Protofire

#931 Update Explorer URLs due to rebranding
  webpack.config.js
Labels: app:Explorer, Protofire

#938 Hotfix/2.5.1 - Rebranding CoW Protocol
  config-default.yaml
  package.json
  src/apps/explorer/layout/Header.tsx
  src/apps/explorer/pages/Home/index.tsx
  src/assets/img/CowProtocol-icon.svg
  src/assets/img/CowProtocol-logo-white.svg
  src/components/layout/GenericLayout/Header/index.tsx
  test/config.spec.ts
  webpack.config.js
Labels: app:Explorer, Protofire

#945 Update URLs barn staging
  webpack.config.js
Labels: app:Explorer, Protofire

#934 [Explorer] Make contracts URLs on footer network aware
  src/api/wallet/WalletApi.ts
  src/components/layout/GenericLayout/Footer/index.tsx
Labels: 🐞 Bug, Protofire, Auto-merge

#946 Fix Logo animation
  src/components/layout/GenericLayout/Header/index.tsx
Labels: app:Explorer, Protofire

#955 Adding queue_rules to mergify file
  .mergify.yml
Labels: app:Explorer, Protofire

#986 Update XDAI, WXDAI and GNO token logos
  src/assets/img/tokens/0x44fa8e6f47987339850636f88629646662444217.png
  src/assets/img/tokens/0x9C58BAcC331c9aa871AFD802DB6379a98e80CEdb.png
  src/assets/img/tokens/0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d.png
  src/assets/img/tokens/xdai.png
  src/components/NetworkSelector/NetworkSelector.styled.ts
  src/components/common/TokenImg.tsx
  src/styles/colours.ts
Labels: app:Explorer, Protofire, Auto-merge, 🔥 Critical

#897 Tx table storybook
  src/apps/explorer/pages/UserDetails.tsx
  src/apps/explorer/pages/styled.tsx
  src/components/common/DateDisplay/index.tsx
  src/components/transaction/TransactionTable/index.stories.tsx
  src/components/transaction/TransactionTable/index.tsx
  src/theme/styles/media.ts
Labels: app:Explorer, Protofire, Auto-merge

#882 transaction view
  src/apps/explorer/ExplorerApp.tsx
  src/apps/explorer/components/TransactionsTableWidget/TransactionsTableWithData.tsx
  src/apps/explorer/components/TransactionsTableWidget/context/TransactionsTableContext.tsx
  src/apps/explorer/components/TransactionsTableWidget/index.tsx
  src/apps/explorer/pages/Home/index.tsx
  src/apps/explorer/pages/NotFound.tsx
  src/apps/explorer/pages/Order.tsx
  src/apps/explorer/pages/SearchNotFound.tsx
  src/apps/explorer/pages/TransactionDetails.tsx
  src/apps/explorer/pages/UserDetails.tsx
  src/apps/explorer/pages/styled.tsx
  src/apps/explorer/styled.ts
  src/components/common/SimpleTable/index.tsx
  src/components/orders/DetailsTable/index.tsx
  src/components/transaction/TransactionTable/index.tsx
  src/theme/styles/media.ts
Labels: app:Explorer, Protofire, Auto-merge
