Repository gnosis/gp-ui, pull requests merged in 2022-03, with the labels that each got.

#1013 reuse useOnClickOutside
  src/apps/explorer/layout/Header.tsx
Labels: app:Explorer, Protofire, Auto-merge

#930 [Explorer] Custom hook for getting explorer data for BlockExplorerLink component when it is not a gpv2 tx
  src/apps/explorer/components/TransactionsTableWidget/index.tsx
  src/components/RedirectToSearch.tsx
  src/components/orders/OrderNotFound/index.tsx
  src/hooks/useGetOrders.tsx
Labels: Protofire, Auto-merge

#1064 Fallback to https over websockets for Infura connection in IOS 15
  src/api/web3/index.ts
  test/api/getProviderByNetwork.test.ts
Labels: Protofire

#1067 [Explorer] Home button redirects to the home page based on the network selected
  src/apps/explorer/layout/Header.tsx
Labels: 🐞 Bug, Protofire, Auto-merge

#1057 Adding requests to the tenderly API
  src/api/baseApi.ts
  src/api/operator/operatorApi.ts
  src/api/tenderly/index.ts
  src/api/tenderly/tenderlyApi.ts
  src/api/tenderly/types.ts
  src/apps/explorer/components/TransactionsTableWidget/index.tsx
  src/const.ts
  src/hooks/useTxBatchTrades.tsx
Labels: app:Explorer, Protofire, Auto-merge

#992 notifications
  src/apps/explorer/components/OrdersTableWidget/context/OrdersTableContext.tsx
  src/apps/explorer/components/OrdersTableWidget/index.tsx
  src/apps/explorer/components/TransactionsTableWidget/context/TransactionsTableContext.tsx
  src/apps/explorer/components/TransactionsTableWidget/index.tsx
  src/apps/explorer/components/common/ExplorerTabs/ExplorerTab.tsx
  src/apps/explorer/pages/UserDetails.tsx
  src/components/ConnectionStatus.tsx
  src/components/Notification.tsx
  src/components/common/Tabs/Tabs.tsx
  src/components/icons/index.tsx
  src/components/orders/OrderDetails/OrderDetails.stories.tsx
  src/components/orders/OrderDetails/index.tsx
  src/hooks/useErc20.ts
  src/hooks/useGetOrders.tsx
  src/hooks/useOperatorOrder.ts
  src/hooks/useOperatorTrades.ts
  src/theme/styles/colours.ts
  src/types/index.ts
Labels: Protofire

#1082 Use creationDate instead of expirationDate on Tx view
  src/components/transaction/TransactionTable/index.tsx
Labels: app:Explorer, Protofire, Auto-merge
